// components/ChatBubble.tsx
import { logger } from "@/utils/logger";
import { useState, useRef, useEffect, useCallback, memo } from "react";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import rehypeHightlight from "rehype-highlight";
import Markdown from "react-markdown";
import BouncingDotsIcon from "@/components/Icon/BouncingDots";
import PencilIcon from "@/components/Icon/Pencil";
import AngleRightIcon from "@/components/Icon/AngleRight";
import AngleLeftIcon from "@/components/Icon/AngleLeft";
import CheckIcon from "@/components/Icon/Check";
import XMarkIcon from "@/components/Icon/XMark";
import CopyIcon from "@/components/Icon/Copy";
import ThumbsUpIcon from "@/components/Icon/ThumbsUp";
import Pre from "@/components/Pre";
import { useSessionStore } from "@/store/sessionStore";
import { LocalMessage } from "@/utils/db/local";

interface ComputedVersionInfo {
  total: number;
  currentIndex: number;
  versionIds: string[];
}

const customComponents = {
  pre({ children, ...props }: React.PropsWithChildren) {
    return <Pre {...props}>{children}</Pre>;
  },
  code({ children, ...props }: React.PropsWithChildren) {
    return (
      <code className="whitespace-pre overflow-x-auto" {...props}>
        {children}
      </code>
    );
  },
};

const MessageContent = memo(
  ({ content, role }: { content: string; role: string }) =>
    role === "user" ? (
      <div className="">{content}</div>
    ) : (
      <Markdown
        remarkPlugins={[remarkGfm, remarkMath]}
        rehypePlugins={[rehypeKatex, rehypeHightlight]}
        components={customComponents}
      >
        {content}
      </Markdown>
    ),
);
MessageContent.displayName = "MessageContent";

const VersionNavigation = memo(
  ({
    versionInfo,
    onBranchChange,
  }: {
    versionInfo?: ComputedVersionInfo;
    onBranchChange: (versionIndex: number) => void;
  }) => {
    const handlePrevVersion = useCallback(() => {
      if (versionInfo && versionInfo.currentIndex !== 0) {
        onBranchChange(
          (versionInfo.currentIndex - 1 + versionInfo.total) %
            versionInfo.total,
        );
      }
    }, [versionInfo, onBranchChange]);

    const handleNextVersion = useCallback(() => {
      if (versionInfo && versionInfo.currentIndex !== versionInfo.total - 1) {
        onBranchChange((versionInfo.currentIndex + 1) % versionInfo.total);
      }
    }, [versionInfo, onBranchChange]);

    // Now conditionally render, after the hooks have been called.
    if (!versionInfo || versionInfo.total <= 1) return null;

    return (
      <div className="flex items-center gap-1">
        <AngleLeftIcon
          fill="var(--main-color)"
          className={`cursor-pointer ${
            versionInfo.currentIndex === 0 ? "opacity-50" : ""
          }`}
          onClick={handlePrevVersion}
        />
        <div className="text-[var(--main-color)]">
          {versionInfo.currentIndex + 1} of {versionInfo.total}
        </div>
        <AngleRightIcon
          fill="var(--main-color)"
          className={`cursor-pointer ${
            versionInfo.currentIndex === versionInfo.total - 1
              ? "opacity-50"
              : ""
          }`}
          onClick={handleNextVersion}
        />
      </div>
    );
  },
);
VersionNavigation.displayName = "VersionNavigation";

function ChatBubble({
  message,
  onEdit,
  versionInfo,
  onBranchChange,
  width,
  maxWidth,
  backgroundColor,
  showName,
}: {
  message: LocalMessage;
  onEdit: (message: LocalMessage) => void;
  versionInfo?: ComputedVersionInfo;
  onBranchChange: (versionIndex: number) => void;
  width?: string;
  maxWidth?: string;
  backgroundColor: string;
  showName: boolean;
}) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(message.content);
  const [isCopied, setIsCopied] = useState(false);
  const [isButtonRowVisible, setIsButtonRowVisible] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const { session } = useSessionStore();

  const handleCopy = useCallback(() => {
    if (!contentRef.current) return;
    navigator.clipboard.writeText(contentRef.current.innerText);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  }, []);

  const interlocutorName =
    message.role === "user" ? session?.user.name || "You" : "Assistant";

  const handleEditClick = useCallback(() => {
    setIsEditing(true);
    setEditedContent(message.content);
    setTimeout(() => {
      if (inputRef.current) {
        inputRef.current.focus();
        inputRef.current.selectionStart = inputRef.current.selectionEnd =
          inputRef.current.value.length;
        inputRef.current.style.height = "auto";
        inputRef.current.style.height = `${inputRef.current.scrollHeight}px`;
      }
    }, 0);
  }, [message.content]);

  const handleSaveEdit = useCallback(() => {
    setIsEditing(false);
    if (editedContent === message.content) return;
    onEdit({ ...message, content: editedContent });
  }, [message, editedContent, onEdit]);

  const handleCancelEdit = useCallback(() => {
    setIsEditing(false);
    setEditedContent(message.content);
  }, [message.content]);

  const handleTextareaKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        handleSaveEdit();
      } else if (e.key === "Escape") {
        handleCancelEdit();
      }
    },
    [handleSaveEdit, handleCancelEdit],
  );

  useEffect(() => {
    setEditedContent(message.content);
  }, [message.content]);

  return (
    <div
      className={`flex cursor-default w-full ${
        message.role === "user" ? "flex-row-reverse" : "flex-row"
      }`}
      onMouseEnter={() => setIsButtonRowVisible(true)}
      onMouseLeave={() => setIsButtonRowVisible(false)}
    >
      <div
        className={`flex flex-col gap-1 ${isEditing && "w-full"} ${
          message.role === "user" ? "items-end" : "items-start"
        }`}
        style={{ width, maxWidth }}
      >
        {showName && <div className="px-1">{interlocutorName}</div>}
        {isEditing ? (
          <div
            className="flex flex-col w-full gap-2 rounded-lg p-2"
            style={{ width, maxWidth: width, backgroundColor }}
          >
            <textarea
              ref={inputRef}
              value={editedContent}
              onChange={(e) => {
                setEditedContent(e.target.value);
                e.target.style.height = "auto";
                e.target.style.height = `${e.target.scrollHeight}px`;
              }}
              onKeyDown={handleTextareaKeyDown}
              className="w-full p-1 focus:outline-none"
            />
            <div className="flex gap-3 justify-end">
              <CheckIcon
                onClick={handleSaveEdit}
                fill="var(--color-yes)"
                className="cursor-pointer scale-125"
              />
              <XMarkIcon
                onClick={handleCancelEdit}
                fill="var(--color-no)"
                className="cursor-pointer scale-125"
              />
            </div>
          </div>
        ) : message.content ? (
          <div
            ref={contentRef}
            className="max-w-full flex flex-col gap-2 rounded-lg p-3"
            style={{ backgroundColor }}
          >
            <MessageContent content={editedContent} role={message.role} />
          </div>
        ) : (
          <div
            className="flex flex-col gap-2 rounded-lg p-3"
            style={{ backgroundColor }}
          >
            <BouncingDotsIcon fill="var(--text-color)" />
          </div>
        )}
        {!isEditing && (
          <div
            className={`flex gap-2 items-center ${
              message.role === "user"
                ? "flex-row-reverse mr-3"
                : "flex-row ml-3"
            }`}
          >
            <VersionNavigation
              versionInfo={versionInfo}
              onBranchChange={onBranchChange}
            />
            {isCopied ? (
              <ThumbsUpIcon
                fill={
                  isButtonRowVisible ? "var(--main-color)" : "var(--bg-color)"
                }
              />
            ) : (
              <CopyIcon
                fill={
                  isButtonRowVisible ? "var(--main-color)" : "var(--bg-color)"
                }
                className="cursor-pointer"
                onMouseDown={(e) => {
                  e.preventDefault();
                  e.stopPropagation();
                  handleCopy();
                }}
              />
            )}
            <PencilIcon
              fill={
                isButtonRowVisible ? "var(--main-color)" : "var(--bg-color)"
              }
              className="cursor-pointer"
              onClick={handleEditClick}
            />
          </div>
        )}
      </div>
    </div>
  );
}

export default memo(ChatBubble);

// components/Chat/Bubble/ChatBubble.vue
<script setup lang="ts">
// Imports
import type { LocalMessage } from "~/utils/db/local";

// Props
const props = defineProps<{
  message: LocalMessage;
  versionInfo?: {
    total: number;
    currentIndex: number;
    versionIds: string[];
  };
}>();

// Definitions
const isButtonRowVisible = ref(false);
const editedContent = ref(props.message.content);
const contentRef = ref<HTMLElement | null>(null);

// Handle copying text to clipboard
const isCopied = ref(false);
function handleCopy() {
  if (!contentRef.value) return;
  navigator.clipboard.writeText(contentRef.value.innerText);
  isCopied.value = true;
  setTimeout(() => (isCopied.value = false), 2000);
}

// Focus the textarea when editing
const isEditing = ref(false);
const textareaRef = ref<HTMLTextAreaElement | null>(null);
watch(isEditing, async (val) => {
  if (val) {
    nextTick(() => {
      textareaRef.value?.focus();
    });
  }
});
</script>

<template>
  <div
    :class="[
      'chat-bubble flex cursor-default w-full',
      message.role === 'user' ? 'flex-row-reverse' : 'flex-row',
    ]"
    @mouseover="isButtonRowVisible = true"
    @mouseleave="isButtonRowVisible = false"
  >
    <div
      :class="[
        'flex flex-col gap-1 w-full',
        isEditing && 'w-full',
        message.role === 'user' ? 'items-end' : 'items-start',
      ]"
    >
      <div
        v-if="isEditing"
        :class="[
          'flex flex-col w-full gap-2 rounded-lg p-2',
          message.role === 'user' && 'bg-(--sub-alt-color)',
        ]"
      >
        <textarea
          v-if="isEditing"
          ref="textareaRef"
          v-model="editedContent"
          class="w-full p-1 focus:outline-none max-h-[600px] resize-none"
          @keydown.enter="
            (e) => {
              if (e.shiftKey) return;
              e.preventDefault();
              isEditing = false;
              handleEditMessage({ ...message, content: editedContent });
            }
          "
        />
        <div class="flex gap-3 justify-end">
          <Icon
            name="lucide:check"
            class="text-(--yes-color) scale-125 cursor-pointer"
            @click="
              () => {
                isEditing = false;
                handleEditMessage({ ...message, content: editedContent });
              }
            "
          />
          <Icon
            name="lucide:x"
            class="text-(--no-color) scale-125 cursor-pointer"
            @click="isEditing = false"
          />
        </div>
      </div>
      <div
        v-else
        :class="[
          'rounded-lg',
          message.role === 'user'
            ? 'max-w-full bg-(--sub-alt-color)'
            : 'w-full',
        ]"
      >
        <div
          v-if="message.content"
          ref="contentRef"
          :class="[
            'flex flex-col gap-2 rounded-lg',
            message.role === 'user' ? 'max-w-full p-3' : 'w-full',
          ]"
          @dblclick="
            () => {
              if (isEditing || message.role !== 'user') return;
              isEditing = true;
            }
          "
        >
          <ChatBubbleContent
            v-if="message.content"
            :content="message.content"
            :role="message.role"
          />
        </div>
        <div v-else class="flex flex-col gap-2 rounded-lg p-3">
          <Icon
            name="svg-spinners:3-dots-bounce"
            class="text-(--main-color) scale-125"
          />
        </div>
      </div>
      <div class="flex">
        <div
          :class="[
            'flex gap-2 items-center',
            message.role === 'user' ? 'flex-row-reverse' : 'flex-row',
          ]"
        >
          <ChatBubbleResponseInfo :model="message.model" />
          <ChatBubbleVersions
            v-if="versionInfo && versionInfo.total > 1"
            :id="message.id"
            :version-info="versionInfo"
          />
          <Icon
            v-if="isCopied"
            name="lucide:thumbs-up"
            :class="[
              'cursor-pointer',
              isButtonRowVisible ? 'text-(--main-color)' : 'text-(--bg-color)',
            ]"
          />
          <Icon
            v-else
            name="lucide:copy"
            :class="[
              'cursor-pointer',
              isButtonRowVisible ? 'text-(--main-color)' : 'text-(--bg-color)',
            ]"
            @mousedown="handleCopy"
          />
          <Icon
            name="lucide:edit"
            :class="[
              'cursor-pointer',
              isButtonRowVisible ? 'text-(--main-color)' : 'text-(--bg-color)',
            ]"
            @click="
              () => {
                isEditing = true;
              }
            "
          />
        </div>
      </div>
    </div>
  </div>
</template>
