// components/ChatList.tsx
"use client";
import { useState, useMemo, useRef } from "react";
import TableListIcon from "@/components/Icon/TableList";
import PlusIcon from "@/components/Icon/Plus";
import ChatListItem from "@/components/ChatListItem";
import ThumbtackIcon from "@/components/Icon/Thumbtack";
import { ChatItem } from "@/app/(auth)/chat/layout";

function ChatListGroupTitle({ title }: { title: string }) {
  return (
    <div className="flex w-full items-center justify-center text-center text-sm font-thin text-(--text-color) mb-1">
      <span className="w-full h-[1px] bg-(--main-color) opacity-50 mx-2" />
      {title === "Pinned" && (
        <ThumbtackIcon fill="var(--main-color)" className="scale-300 mr-2" />
      )}
      <div className="flex justify-center text-nowrap text-(--sub-color)">
        {title}
      </div>
      <span className="w-full h-[1px] bg-(--main-color) opacity-50 mx-2" />
    </div>
  );
}

export default function ChatsPanel({
  chats,
  currentChatId,
  setCurrentChatIdAction,
  isVisible,
  setIsVisibleAction,
  createAction,
  deleteAction,
  renameAction,
  pinAction,
}: {
  chats: ChatItem[];
  currentChatId: string | undefined;
  setCurrentChatIdAction: (sessionId: string) => void;
  isVisible: boolean;
  setIsVisibleAction: (isVisible: boolean) => void;
  createAction: () => void;
  deleteAction: (sessionId: string) => void;
  renameAction: (sessionId: string, newName: string) => void;
  pinAction: (sessionId: string, state: boolean) => void;
}) {
  const minWidth = 250;
  const maxWidth = 600;
  const [sessionPanelWidth, setSessionPanelWidth] = useState(minWidth); // 0 for mobile, 1 for desktop
  const isResizing = useRef(false);

  // Handle panel resizing
  const startResizing = () => {
    isResizing.current = true;

    const handleMouseMove = (e: MouseEvent) => {
      resize(e);
    };

    const handleMouseUp = () => {
      document.removeEventListener("mousemove", handleMouseMove);
      isResizing.current = false;
    };

    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp, { once: true });
  };

  // Resize the panel
  const resize = (event: MouseEvent) => {
    if (!isResizing.current) return;

    let width = 0;

    width = event.clientX;

    let newWidth = width;
    if (width < minWidth / 2) {
      setIsVisibleAction(false);
      newWidth = minWidth;
    } else {
      newWidth = Math.max(minWidth, Math.min(width, maxWidth));
    }
    setSessionPanelWidth(newWidth);
  };

  // Define date boundaries
  const sortedChats: Record<string, ChatItem[]> = useMemo(() => {
    const today = new Date(new Date().setHours(0, 0, 0, 0));
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);
    const lastWeek = new Date(today);
    lastWeek.setDate(lastWeek.getDate() - 7);
    const lastMonth = new Date(today);
    lastMonth.setDate(lastMonth.getDate() - 30);
    return {
      Pinned: chats.filter((chat) => chat.pinned),
      Today: chats.filter((chat) => !chat.pinned && chat.updatedAt >= today),
      Yesterday: chats.filter(
        (chat) =>
          !chat.pinned && chat.updatedAt >= yesterday && chat.updatedAt < today,
      ),
      "Last 7 Days": chats.filter(
        (chat) =>
          !chat.pinned &&
          chat.updatedAt >= lastWeek &&
          chat.updatedAt < yesterday,
      ),
      "Last 30 Days": chats.filter(
        (chat) =>
          !chat.pinned &&
          chat.updatedAt >= lastMonth &&
          chat.updatedAt < lastWeek,
      ),
      Older: chats.filter((chat) => !chat.pinned && chat.updatedAt < lastMonth),
    };
  }, [chats]);

  return (
    <div
      className={`h-full bg-(--sub-alt-color) ${isVisible ? "flex" : "hidden"}`}
    >
      <div
        className="flex justify-center p-2 overflow-hidden"
        style={{ width: sessionPanelWidth }}
      >
        <div className="flex flex-col w-full items-center gap-2">
          <div className="flex w-full items-center px-2">
            <TableListIcon
              fill="var(--main-color)"
              className="cursor-pointer"
              onMouseDown={() => setIsVisibleAction(false)}
            />
            <div className="grow text-center">Chats</div>
            <PlusIcon
              fill="var(--main-color)"
              className="cursor-pointer"
              onClick={createAction}
            />
          </div>
          <div className="w-full h-[1px] bg-(--main-color) opacity-50" />
          {/* Sessions List */}
          <div className="flex flex-col w-full gap-2">
            {Object.keys(sortedChats).map((key) => {
              return sortedChats[key].length > 0 ? (
                <div
                  key={key}
                  className="flex flex-col w-full text-center text-sm mb-2"
                >
                  <ChatListGroupTitle title={key} />
                  {sortedChats[key].map((chat) => (
                    <ChatListItem
                      key={chat.id}
                      chat={chat}
                      currentChatSessionId={currentChatId}
                      setCurrentChatSessionId={setCurrentChatIdAction}
                      deleteHandler={deleteAction}
                      renameHandler={renameAction}
                      pinHandler={pinAction}
                    />
                  ))}
                </div>
              ) : null;
            })}
          </div>
        </div>
      </div>
      <div
        className="flex cursor-ew-resize"
        onMouseDown={(e) => {
          e.preventDefault();
          startResizing();
        }}
      >
        {/* Some trickery to create a 1px border with a wide hover range*/}
        <div className="w-[3px] bg-(--sub-alt-color)" />
        <div className="w-[3px] bg-(--bg-color)" />
      </div>
    </div>
  );
}

// app/components/Chat/ChatList.vue
<script setup lang="ts">
const chatStore = useChatStore();
const sortedChats = computed(() => {
  const today = new Date(new Date().setHours(0, 0, 0, 0));
  const yesterday = new Date(today);
  yesterday.setDate(yesterday.getDate() - 1);
  const lastWeek = new Date(today);
  lastWeek.setDate(lastWeek.getDate() - 7);
  const lastMonth = new Date(today);
  lastMonth.setDate(lastMonth.getDate() - 30);
  const sortedChats = Object.values(chatStore.chats).sort(
    (a, b) => b.updatedAt.getTime() - a.updatedAt.getTime(),
  );
  return {
    Pinned: sortedChats.filter((chat) => chat.pinned),
    Today: sortedChats.filter(
      (chat) => !chat.pinned && chat.updatedAt >= today,
    ),
    Yesterday: sortedChats.filter(
      (chat) =>
        !chat.pinned && chat.updatedAt >= yesterday && chat.updatedAt < today,
    ),
    "Last 7 Days": sortedChats.filter(
      (chat) =>
        !chat.pinned &&
        chat.updatedAt >= lastWeek &&
        chat.updatedAt < yesterday,
    ),
    "Last 30 Days": sortedChats.filter(
      (chat) =>
        !chat.pinned &&
        chat.updatedAt >= lastMonth &&
        chat.updatedAt < lastWeek,
    ),
    Older: sortedChats.filter(
      (chat) => !chat.pinned && chat.updatedAt < lastMonth,
    ),
  };
});

const chatListRef = ref<HTMLElement | null>(null);
const resizerRef = ref<HTMLElement | null>(null);

const minWidth = 250;
const maxWidth = 600;
const uiStore = useUiStore();

useDraggable(resizerRef, {
  preventDefault: true,
  onMove: (position) => {
    if (position.x < minWidth / 2) {
      uiStore.setChatListWidth(minWidth);
      uiStore.setChatListVisible(false);
    } else {
      uiStore.setChatListWidth(
        Math.max(minWidth, Math.min(position.x, maxWidth)),
      );
    }
  },
});
</script>

<template>
  <div
    ref="chatListRef"
    class="chat-list h-full bg-(--sub-alt-color)"
    :style="{
      display: uiStore.chatListVisible ? 'flex' : 'none',
    }"
  >
    <div
      class="flex flex-col grow w-full"
      :style="{ width: uiStore.chatListWidth + 'px' }"
    >
      <div class="flex w-full h-[40px] items-center px-4">
        <Icon
          name="lucide:panel-left-close"
          class="text-(--main-color) cursor-pointer scale-125"
          @click="uiStore.setChatListVisible(false)"
        />
        <div class="grow text-center">chats</div>
        <Icon
          name="lucide:plus"
          class="text-(--main-color) cursor-pointer scale-125"
          @click="
            async () => {
              navigateTo('/chat');
            }
          "
        />
      </div>
      <div class="flex flex-col p-2 overflow-y-auto overflow-x-hidden">
        <div class="flex flex-col w-full items-center gap-2">
          <div class="flex flex-col w-full gap-2">
            <div
              v-for="[groupName, group] of Object.entries(sortedChats)"
              :key="groupName"
              class="flex flex-col w-full gap-2"
            >
              <ChatListGroupTitle v-if="group.length" :title="groupName" />
              <ChatListItem
                v-for="chat of group"
                :key="chat.id"
                :chat="chat"
                @mousedown="
                  async () => {
                    navigateTo('/chat/' + chat.id);
                  }
                "
                @touchstart="
                  async () => {
                    navigateTo('/chat/' + chat.id);
                    uiStore.setChatListVisible(false);
                  }
                "
              />
            </div>
            <div id="bottom" class="h-[100px]" />
          </div>
        </div>
      </div>
    </div>
    <div
      ref="resizerRef"
      class="flex w-[3px] shrink-0 cursor-ew-resize bg-(--bg-color) hover:bg-(--main-color)!"
    />
  </div>
</template>

<style scoped>
.chat-list ::-webkit-scrollbar-track {
  background: var(--sub-alt-color);
}

.chat-list ::-webkit-scrollbar-thumb {
  border: solid 5px var(--sub-alt-color);
}
</style>
