// app/components/Chat/ChatList/ChatListItem.vue
<script setup lang="ts">
import { dbUpdateChat } from "~/utils/db/local";
const props = defineProps<{
  chat: ChatState;
}>();

const newTitle = ref(props.chat.title);
watch(
  () => props.chat.title,
  (title) => {
    if (!isRenaming.value) {
      newTitle.value = title;
    }
  },
);

const isRenaming = ref(false);
const isHovered = ref(false);
const inputRef = ref<HTMLInputElement | null>(null);

const chatStore = useChatStore();
</script>

<template>
  <div
    :class="[
      'w-full flex gap-1.5 justify-between items-center rounded-lg p-1.5 cursor-pointer chat-list-item',
      `${chatStore.currentChatId === chat.id && 'bg-(--bg-color)'}`,
    ]"
    @dblclick="
      () => {
        isRenaming = true;
        nextTick(() => {
          inputRef?.focus();
        });
      }
    "
    @mouseover="isHovered = true"
    @mouseleave="isHovered = false"
  >
    <div class="flex cursor-pointer hover:opacity-80 overflow-hidden w-full">
      <input
        v-if="isRenaming"
        ref="inputRef"
        v-model="newTitle"
        type="text"
        class="grow border border-(--sub-color) p-1 rounded w-full chat-list-item-input"
        @keydown.escape="
          () => {
            isRenaming = false;
            newTitle = chat.title;
          }
        "
        @keydown.enter="
          () => {
            chatStore.updateChatMetadata(chat.id, {
              title: newTitle,
            });
            dbUpdateChat(chat.id, { title: newTitle });
            isRenaming = false;
          }
        "
      />
      <div
        v-else
        class="flex gap-1.5 items-center truncate chat-list-item-title"
      >
        <div class="w-full truncate">
          {{ chat.title }}
        </div>
        <Icon
          v-if="chat.isStreaming"
          name="svg-spinners:6-dots-scale"
          class="text-(--main-color) scale-125"
        />
      </div>
    </div>
    <div v-if="isRenaming" class="flex gap-1.5 items-center">
      <button
        class="flex items-center cursor-pointer p-0! m-0! hover:bg-(--bg-color)!"
      >
        <Icon
          name="lucide:check"
          class="text-(--yes-color) scale-125"
          @click="
            () => {
              chatStore.updateChatMetadata(chat.id, {
                title: newTitle,
              });
              dbUpdateChat(chat.id, { title: newTitle });
              isRenaming = false;
            }
          "
        />
      </button>
      <button
        class="flex items-center cursor-pointer p-0! m-0! hover:bg-(--bg-color)!"
      >
        <Icon
          name="lucide:x"
          class="text-(--no-color) scale-125 cursor-pointer"
          @click="
            () => {
              newTitle = chat.title;
              isRenaming = false;
            }
          "
        />
      </button>
    </div>
    <ChatListItemDropdown
      v-else
      :chat="chat"
      :is-hovered="isHovered"
      @rename="isRenaming = true"
    />
  </div>
</template>

// components/ChatListItem.tsx
import { useState, useRef, useEffect } from "react";
import DotsIcon from "@/components/Icon/Dots";
import TrashCanIcon from "@/components/Icon/TrashCan";
import PencilIcon from "@/components/Icon/Pencil";
import CheckIcon from "@/components/Icon/Check";
import XMarkIcon from "@/components/Icon/XMark";
import DropDownMenu, {
  DropDownMenuButton,
  DropDownMenuItem,
  DropDownMenuList,
} from "@/components/DropDownMenu";
import { LocalChat } from "@/utils/db/localDb";

export default function ChatListItem({
  session,
  currentChatSessionId,
  setCurrentChatSessionId,
  deleteHandler,
  renameHandler,
}: {
  session: LocalChat;
  currentChatSessionId: string | undefined;
  setCurrentChatSessionId: (sessionId: string) => void;
  deleteHandler: (sessionId: string) => void;
  renameHandler: (sessionId: string, newTitle: string) => void;
}) {
  const [isRenaming, setIsRenaming] = useState(false);
  const [isMenuButtonVisible, setIsMenuButtonVisible] = useState(false);
  const [newTitle, setNewTitle] = useState(session.title);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isRenaming) {
      inputRef.current?.focus();
    }
  }, [isRenaming]);

  useEffect(() => {
    setNewTitle(session.title);
  }, [session.title]);

  return (
    <div
      className={`flex gap-1 justify-between items-center rounded-lg p-1.5 cursor-pointer ${currentChatSessionId === session.id && "bg-(--color-bg2)"}`}
      onMouseEnter={() => setIsMenuButtonVisible(true)}
      onMouseLeave={() => setIsMenuButtonVisible(false)}
      onMouseDown={() => setCurrentChatSessionId(session.id)}
    >
      <div className="cursor-pointer hover:opacity-80 overflow-hidden">
        {isRenaming ? (
          <input
            type="text"
            ref={inputRef}
            value={newTitle}
            onChange={(e) => setNewTitle(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === "Enter") {
                if (session.title !== newTitle) {
                  renameHandler(session.id, newTitle);
                }
                setIsRenaming(false);
              } else if (e.key === "Escape") {
                setNewTitle(session.title);
                setIsRenaming(false);
              }
            }}
            className="border px-1 rounded w-full border-none"
          />
        ) : (
          <div className="text-nowrap overflow-hidden text-ellipsis">
            {newTitle}
          </div>
        )}
      </div>
      {isRenaming ? (
        <div className="flex">
          <button
            onClick={() => {
              if (session.title !== newTitle) {
                renameHandler(session.id, newTitle);
              }
              setIsRenaming(false);
            }}
            onMouseDown={(e) => e.stopPropagation()}
            className="p-1 cursor-pointer"
          >
            <CheckIcon fill="var(--color-yes)" />
          </button>
          <button
            onClick={() => {
              setNewTitle(session.title);
              setIsRenaming(false);
            }}
            onMouseDown={(e) => e.stopPropagation()}
            className="p-1 cursor-pointer"
          >
            <XMarkIcon fill="var(--color-no)" />
          </button>
        </div>
      ) : (
        <DropDownMenu>
          <DropDownMenuButton>
            {isMenuButtonVisible ? (
              <DotsIcon fill="var(--color-acc)" className="scale-125" />
            ) : (
              <DotsIcon
                fill={`${currentChatSessionId === session.id && "bg-(--color-bg2)"}`}
              />
            )}
          </DropDownMenuButton>
          <DropDownMenuList align="right">
            <DropDownMenuItem
              onClick={(e) => {
                e.stopPropagation();
                e.preventDefault();
                setIsRenaming(true);
              }}
              onMouseDown={(e) => {
                e.stopPropagation();
              }}
            >
              <div className="grid grid-cols-[20px_auto] items-center ">
                <PencilIcon fill="var(--color-acc)" />
                Rename
              </div>
            </DropDownMenuItem>
            <DropDownMenuItem onClick={() => deleteHandler(session.id)}>
              <div className="grid grid-cols-[20px_auto] items-center text-(--error-color)">
                <TrashCanIcon
                  fill="var(--color-no)"
                  className="translate-y-[-1px]"
                />
                Trash
              </div>
            </DropDownMenuItem>
          </DropDownMenuList>
        </DropDownMenu>
      )}
    </div>
  );
}
